//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.18 at 12:35:08 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.imageViewer.mx/schema/gestioneOpera", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.imageviewer.schema.gestioneopera;
